### ISSUE TITLE
elm-test seems to be broken

### ISSUE THREAD

**Issue by francisdb** [maport/docker-elm#6]
tag `0.18`

```
+ elm-test tests/*.elm
Starting downloads...
...
Success! Compiled 67 modules.
Successfully generated /tmp/elm_test_117829-23-1onzyyw.i464huayvi.js
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: testModule.worker is not a function
(node:23) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

also upgrading elm-test fails

```
+ npm install -g elm-test
npm info it worked if it ends with ok
npm info using npm@3.10.9
...
> elm-test@0.18.9 install /usr/local/lib/node_modules/elm-test
> node install.js
module.js:472
    throw err;
    ^
Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/elm-test/node_modules/verror/lib/verror.js:9:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm info lifecycle elm-test@0.18.9~install: Failed to exec install script
```

**Comment by blisscs** [comment]
Hi @francisdb,
Have to figure how to resolve this. I am getting the same issue.

Dev.

**Comment by francisdb** [comment]
Last time I was playing with elm I switched to `codesimple/elm:0.18`

**Comment by blisscs** [comment]
Ok, I will try that. 
I did however switch to the latest node image. then install both elm and elm-test and ran test, and this issue didn't come up.

Thanks
Dev
